name: Main test action

on:
  issues:
  pull_request:
    types:
        - opened
        - edited
        - synchronize
  pull_request_review:
  pull_request_review_comment:

jobs:
  run-reviewpad:
    runs-on: ubuntu-latest
    steps:
      - name: Run reviewpad action
        uses: reviewpad/action@experimental