name: Reviewpad action

on:
  issues:
    types:
      - opened
      - edited
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft
      - edited
      - review_requested
      - review_request_removed
  pull_request_review:
  pull_request_review_comment:

jobs:
  run-reviewpad:
    runs-on: ubuntu-latest
    steps:
      - name: Run reviewpad action
        uses: reviewpad/action@canary