name: Reviewpad action

on:
  pull_request:
    types:
      - opened
      - edited
      - closed
      - synchronize
  pull_request_review:

jobs:
  reviewpad:
    runs-on: ubuntu-latest
    steps:
      - name: Running reviewpad action
        uses: reviewpad/action-dev:dev_pipelines
