name: Test workflows

on:
  - branch_protection_rule
  - check_run
  - check_suite
  - create
  - delete
  - deployment
  - deployment_status
  - discussion
  - discussion_comment
  - fork
  - gollum
  - issue_comment
  - issues
  - label
  - merge_group
  - milestone
  - page_build
  - project
  - project_card
  - project_column
  - public
  - pull_request
  - pull_request_review
  - pull_request_review_comment
  - pull_request_target
  - push
  - registry_package
  - release
  - repository_dispatch
  - status
  - watch
  - workflow_call
  - workflow_dispatch
  - workflow_run

    
  # pull_request:
  #   types: [ labeled, opened, synchronize, reopened ]

jobs:
  test:
    # if: ${{ github.event.label.name == 'run-build' || github.event }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'